---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "devopsrep-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "devopsrep"
  template:
    metadata:
      labels:
        app: "devopsrep"
    spec:
      containers:
        - image: "nginx:alpine"
          name: nginx
          ports:
            - containerPort: 80
 
---
apiVersion: v1
kind: Service
metadata:
  name: "devopsrep-service"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: "devopsrep"
