# This is an example of a deployment - a declaration of pods.
---
apiVersion: v1
kind: Deployment
metadata:
  name: "devopsrep-deployment"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "devopsrep-2"
  template:
    metadata:
      labels:
        app: "devopsrep-2"
    spec:
      containers:
        - image: "nginx:alpine"
          name: nginx
          ports:
            - containerPort: 80
 
